# Generated by Django 4.1 on 2024-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationrecord',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
