# Generated by Django 4.1 on 2024-07-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_locationrecord_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basedate', models.CharField(help_text='기준 날짜', max_length=10)),
                ('basetime', models.CharField(help_text='기준 시간', max_length=10)),
                ('weather_code', models.CharField(help_text='날씨 코드', max_length=10)),
                ('fcstdate', models.CharField(help_text='예보 날짜', max_length=10)),
                ('fcsttime', models.CharField(help_text='예보 시간', max_length=10)),
                ('fcstvalue', models.CharField(help_text='예보 값', max_length=10)),
                ('nx', models.CharField(help_text='nx', max_length=3)),
                ('ny', models.CharField(help_text='ny', max_length=3)),
            ],
        ),
    ]
