# Generated by Django 4.1 on 2024-07-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'managed': False},
        ),
    ]
