# Generated by Django 4.1 on 2024-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_weatherdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin', models.CharField(max_length=50)),
                ('law_id', models.CharField(max_length=50)),
                ('fct_id', models.CharField(max_length=50)),
                ('stn_en', models.CharField(max_length=100)),
                ('stn_ko', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'weather_stn',
                'managed': False,
            },
        ),
    ]
