# Generated by Django 4.1 on 2024-07-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_weatherstation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherstation',
            table='raw_data.weather_stn',
        ),
    ]
