# Generated by Django 4.1 on 2024-07-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_weatherstation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table='raw_data.weather_stn',
        ),
        migrations.AlterModelTable(
            name='weatherstation',
            table='weather_stn',
        ),
    ]
