# Generated by Django 4.1 on 2024-07-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_weatherdata_table_alter_weatherstation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table=None,
        ),
    ]
