# Generated by Django 4.1 on 2024-07-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_raw_data_weatherstn'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='raw_data_weatherstn',
            table='public.raw_data.weather_stn',
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table='raw_data.weather_data',
        ),
        migrations.AlterModelTable(
            name='weatherstation',
            table='public.weather_stn',
        ),
    ]
