# Generated by Django 4.1 on 2024-07-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_alter_raw_data_weatherstn_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table='weather_data',
        ),
    ]
