# Generated by Django 4.1 on 2024-07-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_alter_weatherdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='raw_data_weatherstn',
            table='raw_data.weather_stn',
        ),
        migrations.AlterModelTable(
            name='weatherstation',
            table='weather_stn',
        ),
    ]
