# Generated by Django 4.1 on 2024-07-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_alter_raw_data_weatherstn_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raw_data_WeatherStn',
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
    ]
