# Generated by Django 4.1 on 2024-07-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_delete_raw_data_weatherstn_delete_weatherstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='musinsaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_link', models.TextField()),
                ('image_link', models.TextField()),
                ('rank', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('data_creation_time', models.DateTimeField()),
                ('category', models.TextField()),
                ('price', models.IntegerField()),
                ('gender', models.TextField()),
            ],
            options={
                'db_table': 'musinsa',
            },
        ),
    ]
