# Generated by Django 4.1 on 2024-07-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_musinsadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musinsadata',
            options={'managed': False},
        ),
    ]
