# Generated by Django 4.1 on 2024-08-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_alter_musinsadata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='weatherCategorizeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weather_info', models.TextField()),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'weather_categorize',
                'managed': False,
            },
        ),
    ]
