# Generated by Django 4.1 on 2024-08-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_locationrecord_session'),
        ('weather', '0016_weathercategorizedata'),
    ]

    operations = [
    ]
