# Generated by Django 4.1 on 2024-08-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_merge_20240805_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationrecord',
            name='session',
        ),
    ]
