# Generated by Django 4.2 on 2024-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0018_remove_locationrecord_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65535)),
                ('description', models.CharField(max_length=65535)),
                ('link', models.CharField(max_length=65535)),
                ('pubDate', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=65535)),
            ],
            options={
                'db_table': 'news_weather_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherStn',
            fields=[
                ('location1', models.CharField(help_text='location1', max_length=10)),
                ('location2', models.CharField(help_text='location2', max_length=10)),
                ('location3', models.CharField(help_text='location3', max_length=10)),
                ('nx', models.CharField(help_text='nx', max_length=10)),
                ('ny', models.CharField(help_text='ny', max_length=10)),
                ('lon', models.CharField(help_text='lon', max_length=10, primary_key=True, serialize=False)),
                ('lat', models.CharField(help_text='lat', max_length=10)),
            ],
            options={
                'db_table': 'weather_stn',
                'managed': False,
            },
        ),
    ]
