name: Sync DAGs to S3

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'airflow/**'
  
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      # checkout을 이용해 코드에 접근
      - name: Checkout files
        uses: actions/checkout@v3

      # aws-actions을 이용해 aws credentials 획득
      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      # S3에 업로드
      - name: Sync to S3
        run: aws s3 sync ./airflow/dag s3://${{ secrets.AWS_BUCKET }}/${{ secrets.AWS_DESTINATION_KEY }} --delete
