name: Django CI

on:
  push:
    branches: [ "develop", "main" ]
    paths: 
      - 'django_file/**'
    
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'django_file/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GCP
      env:
        DJANGO_SETTINGS_MODULE: django_file.settings
      run: |
        gcloud compute ssh --project ${{ secrets.GCP_PROJECT_ID }} --zone asia-northeast3-a instance-temp-trend -- 'bash -s' << EOF
          cd /home/junghwa010609/django
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/Programmers-FinalProject/Temp_Trend.git
            git config core.sparseCheckout true
            echo 'django_file/*' >> .git/info/sparse-checkout
          fi
          git pull origin develop
          cd django_file
          source venv/bin/activate
          if git diff --name-only HEAD~1 | grep -q 'requirements.txt'; then
            pip install -r requirements.txt
          else
            echo "requirements.txt did not change, skipping install."
          fi
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
