name: Build and Deploy to Google Compute Engine

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'django_file/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'django_file/**'

env:
  GCE_INSTANCE: instance-temp-trend # TODO: update to instance name
  GCE_INSTANCE_ZONE: asia-northeast3-a # TODO: update to instance zone

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      # Setup gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Start GCE instance
        run: |
          gcloud compute instances start ${{ env.GCE_INSTANCE }} --zone ${{ env.GCE_INSTANCE_ZONE }}
      
      - name: Deploy to GCE
        run: |
          gcloud compute ssh --quiet --zone asia-northeast3-a instance-temp-trend --command "
              cd /home/junghwa010609/django &&
              git checkout develop &&
              git pull origin develop &&
              cd django_file &&
              source venv/bin/activate &&
              if git diff --name-only HEAD@{1} HEAD | grep -q 'requirements.txt'; then
                pip install -r requirements.txt
              fi &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              sudo systemctl restart gunicorn &&
              sudo systemctl restart nginx
              "