name: Django CI

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'django_file/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'django_file/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create SSH directory
      run: mkdir -p ~/.ssh
    
    - name: Set up SSH private key
      run: |
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
        chmod 600 ~/.ssh/google_compute_engine
      shell: bash
    
    - name: Set up SSH public key
      run: |
        echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ~/.ssh/google_compute_engine.pub
        chmod 644 ~/.ssh/google_compute_engine.pub
      shell: bash
    
    - name: Test GCP Access
      run: |
        gcloud compute instances list --project ${{ secrets.GCP_PROJECT_ID }} --zone asia-northeast3-a
      shell: bash
    
    - name: Test SSH Connection
      run: |
        gcloud compute ssh instance-temp-trend --project ${{ secrets.GCP_PROJECT_ID }} --zone asia-northeast3-a --command "echo 'SSH connection successful'"
      shell: bash

    - name: Network Diagnostics
      run: |
        echo "Checking DNS..."
        nslookup compute.googleapis.com
        
        echo "Tracing route..."
        traceroute compute.googleapis.com
        
        echo "Checking HTTPS connection..."
        curl -v https://compute.googleapis.com
        
        echo "Checking GCP authentication..."
        gcloud auth list
        gcloud config list project
      shell: bash

    - name: Test connection to compute.googleapis.com
      run: ping -c 4 compute.googleapis.com
      shell: bash
    
    - name: Add compute.googleapis.com to known hosts
      run: |
        ssh-keyscan -v -H compute.googleapis.com >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
      shell: bash
    
    - name: Test ssh-keyscan
      run: |
        ssh-keyscan -v -H github.com >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
      shell: bash  

    - name: Debug SSH setup
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/google_compute_engine.pub
      shell: bash
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Deploy to GCP
      env:
        DJANGO_SETTINGS_MODULE: django_file.settings
      run: |
        gcloud compute ssh junghwa010609@instance-temp-trend --project ${{ secrets.GCP_PROJECT_ID }} --zone asia-northeast3-a -- '
          set -e
          cd /home/junghwa010609/django
          git fetch origin develop
          git checkout develop || git checkout -b develop origin/develop
          git pull origin develop
          cd django_file
          source venv/bin/activate
          if git diff --name-only HEAD@{1} HEAD | grep -q "requirements.txt"; then
            pip install -r requirements.txt
          fi
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          echo "Deployment completed successfully"
        '
      shell: bash