name: Django CI

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'django_file/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'django_file/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
        echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ~/.ssh/google_compute_engine.pub
        chmod 600 ~/.ssh/google_compute_engine
        chmod 644 ~/.ssh/google_compute_engine.pub
        ssh-keyscan -H compute.googleapis.com >> ~/.ssh/known_hosts
      shell: bash
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Verify GCP setup
      run: |
        gcloud info
        gcloud auth list
        gcloud config list
        gcloud compute instances list
      shell: bash
    
    - name: Network Diagnostics
      run: |
        echo "Checking DNS..."
        nslookup compute.googleapis.com
        echo "Checking connectivity..."
        ping -c 4 compute.googleapis.com
      shell: bash

    - name: Deploy to GCP
      env:
        DJANGO_SETTINGS_MODULE: django_file.settings
      run: |
        gcloud compute ssh junghwa010609@instance-temp-trend --project ${{ secrets.GCP_PROJECT_ID }} --zone asia-northeast3-a -- '
          set -e
          cd /home/junghwa010609/django
          git fetch origin develop
          git checkout develop || git checkout -b develop origin/develop
          git pull origin develop
          cd django_file
          source venv/bin/activate
          if git diff --name-only HEAD@{1} HEAD | grep -q "requirements.txt"; then
            pip install -r requirements.txt
          fi
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          echo "Deployment completed successfully"
        '
      shell: bash