name: Build and Deploy to Google Compute Engine

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'django_file/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'django_file/**'

env:
  GCE_INSTANCE: instance-temp-trend # TODO: update to instance name
  GCE_INSTANCE_ZONE: asia-northeast3-a # TODO: update to instance zone

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      # Setup gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/temp_trend_key
          chmod 600 ~/.ssh/temp_trend_key
          echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ~/.ssh/temp_trend_key.pub
          chmod 644 ~/.ssh/temp_trend_key.pub
          ssh-keyscan -H compute.googleapis.com >> ~/.ssh/known_hosts
      
      - name: Deploy to GCE
        run: |
          gcloud compute ssh --zone ${{ env.GCE_INSTANCE_ZONE }} ${{ env.GCE_INSTANCE }} --ssh-key-file=gce_key -- '
            cd /home/junghwa010609/django &&
            git pull origin develop &&
            cd django_file
            source venv/bin/activate &&
            if git diff --name-only HEAD@{1} HEAD | grep -q "requirements.txt"; then
              pip install -r requirements.txt
            fi
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            sudo systemctl restart gunicorn &&
            sudo systemctl restart nginx
            echo "Deployment completed successfully"